name : actionpr
on:
 push: 
  branches:
   - main
 pull_request:
  branches:
   - main
 workflow_dispatch:
 schedule:
  - cron: "0 0 * * *"
jobs:
 firstjob:
  runs-on: ubuntu-latest
  steps:
  - name: printhello
    run: echo "hello world"
 secondjob:
   runs-on: ubuntu-latest
   steps:
    - name: envandsecrets
    - env: 
       NAME: "chiku"
       PASSWORD: ${{secrets.MY_NAME}}
       run: |
         echo "name is$name"
         echo "PASSWORD IS $PASSWORD
       
      
       
  
 
