name : actionpr
on:
 push: 
  branches:
   - main
 pull_request:
  branches:
   - main
 workflow_dispatch:
 schedule:
  - cron: "0 0 * * *"
jobs:
 firstjob:
 runs-on: ubuntu-latest
    steps:
     - name: printhello
       run: echo "hello world"
  
 
